In [1]:
import numpy as np

#### Create a numpy array containing ingredients of a cupcake

In [2]:
cupcakes = np.array([2,0.75,2,1,0.5])

In [3]:
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

In [4]:
#Load from external csv file
recipes = np.genfromtxt('recipes.csv',
                        delimiter=',')

In [5]:
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

Create a numpy array containing only eggs which is the 3rd Column of the recipes array

In [6]:
eggs = recipes[:,2]
eggs

array([2., 1., 1., 2.])

In [7]:
#Find columns with only 1 egg
eggs==1

array([False,  True,  True, False])

In [8]:
#Find out the entire rows containing only 1 egg
one_egg = recipes[(eggs==1)]
one_egg

array([[1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ]])

Filter out the cookies recipe which is the 3rd row

In [9]:
cookies = recipes[2,:]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

In [10]:
# multiply every element in the cupcakes array by 2
double_batch = cupcakes * 2
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

Create a shopping list array for a double batch of cupcakes and cookies. Basically adding the two arrays for getting the total ingredients

In [11]:
shopping_list = cookies + double_batch
shopping_list

array([6.75, 3.  , 5.  , 2.  , 2.  ])