[View in Colaboratory](https://colab.research.google.com/github/averma12/Beginning_Data_Science/blob/master/Softmax_cross_entropy.ipynb)

In [0]:
import numpy as np
N = 100 # number of points per class
D = 2 # dimensionality
K = 3 # number of classes
X = np.zeros((N*K,D)) # data matrix (each row = single example)
y = np.zeros(N*K, dtype='uint8') # class labels
for j in range(K):
  ix = range(N*j,N*(j+1))
  r = np.linspace(0.0,1,N) # radius
  t = np.linspace(j*4,(j+1)*4,N) + np.random.randn(N)*0.2 # theta
  X[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
  y[ix] = j

In [0]:
W = 0.01 * np.random.randn(D,K)
b = np.zeros((1,K))

In [0]:
scores = np.dot(X, W) + b

In [5]:
scores.shape

(300, 3)

In [0]:
num_examples = X.shape[0]
# get unnormalized probabilities
exp_scores = np.exp(scores)
# normalize them for each example
probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

In [23]:
probs

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33332965, 0.33331624, 0.33335412],
       [0.33333637, 0.333297  , 0.33336664],
       [0.33332865, 0.33328039, 0.33339096],
       [0.33337982, 0.33326361, 0.33335657],
       [0.33339025, 0.33324584, 0.33336391],
       [0.33333765, 0.33322495, 0.3334374 ],
       [0.33339821, 0.33320748, 0.33339431],
       [0.33346632, 0.33321204, 0.33332163],
       [0.33334297, 0.33317033, 0.33348671],
       [0.33346375, 0.33316375, 0.3333725 ],
       [0.33351935, 0.33316868, 0.33331197],
       [0.33351532, 0.33314115, 0.33334353],
       [0.33348167, 0.33310598, 0.33341235],
       [0.33357637, 0.33312824, 0.33329539],
       [0.3334954 , 0.3330686 , 0.333436  ],
       [0.33366003, 0.33314758, 0.3331924 ],
       [0.33355369, 0.33304456, 0.33340175],
       [0.33365919, 0.33308015, 0.33326066],
       [0.33366035, 0.33305293, 0.33328672],
       [0.33375389, 0.3331192 , 0.33312691],
       [0.3336552 , 0.33299882, 0.33334598],
       [0.

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In [0]:
correct_logprobs = -np.log(probs[range(num_examples),y])

In [17]:
probs[range(300),y]

array([0.33333333, 0.33332965, 0.33333637, 0.33332865, 0.33337982,
       0.33339025, 0.33333765, 0.33339821, 0.33346632, 0.33334297,
       0.33346375, 0.33351935, 0.33351532, 0.33348167, 0.33357637,
       0.3334954 , 0.33366003, 0.33355369, 0.33365919, 0.33366035,
       0.33375389, 0.3336552 , 0.33364247, 0.33381927, 0.33368591,
       0.33381748, 0.33385364, 0.33387051, 0.33386039, 0.33390142,
       0.33396927, 0.33403933, 0.33406604, 0.33408176, 0.33409553,
       0.33412598, 0.33413283, 0.33417028, 0.33420324, 0.33414298,
       0.33424392, 0.33424531, 0.33424711, 0.33423155, 0.33431305,
       0.33428657, 0.33432273, 0.33438859, 0.33427281, 0.33427318,
       0.33425451, 0.33450331, 0.33414668, 0.33417317, 0.33420564,
       0.33426607, 0.33403026, 0.33391334, 0.33406933, 0.33402531,
       0.33405506, 0.33421876, 0.33416664, 0.33425616, 0.33324912,
       0.33358314, 0.33381846, 0.33326583, 0.33361733, 0.33374454,
       0.33434299, 0.33348195, 0.33365327, 0.33322446, 0.33251

In [21]:
x = np.array([[1, 2,3], [3, 4,8], [5, 6,9]])
x[[0, 2, 2], [2, 1, 0]]
probs[0,0],probs[1,0],probs[2,0]

(0.3333333333333333, 0.3333296464656622, 0.3333363673012898)

In [22]:
probs[range(300),y]

array([0.33333333, 0.33332965, 0.33333637, 0.33332865, 0.33337982,
       0.33339025, 0.33333765, 0.33339821, 0.33346632, 0.33334297,
       0.33346375, 0.33351935, 0.33351532, 0.33348167, 0.33357637,
       0.3334954 , 0.33366003, 0.33355369, 0.33365919, 0.33366035,
       0.33375389, 0.3336552 , 0.33364247, 0.33381927, 0.33368591,
       0.33381748, 0.33385364, 0.33387051, 0.33386039, 0.33390142,
       0.33396927, 0.33403933, 0.33406604, 0.33408176, 0.33409553,
       0.33412598, 0.33413283, 0.33417028, 0.33420324, 0.33414298,
       0.33424392, 0.33424531, 0.33424711, 0.33423155, 0.33431305,
       0.33428657, 0.33432273, 0.33438859, 0.33427281, 0.33427318,
       0.33425451, 0.33450331, 0.33414668, 0.33417317, 0.33420564,
       0.33426607, 0.33403026, 0.33391334, 0.33406933, 0.33402531,
       0.33405506, 0.33421876, 0.33416664, 0.33425616, 0.33324912,
       0.33358314, 0.33381846, 0.33326583, 0.33361733, 0.33374454,
       0.33434299, 0.33348195, 0.33365327, 0.33322446, 0.33251

In [33]:
correct_logprobs

array([1.09861229, 1.09858152, 1.09854018, 1.09850528, 1.09848518,
       1.09849185, 1.09841091, 1.098424  , 1.09836945, 1.09830211,
       1.09826831, 1.09827429, 1.09826418, 1.09825938, 1.09828233,
       1.09845098, 1.09825541, 1.09840755, 1.09827147, 1.09812936,
       1.09830661, 1.09793977, 1.09821316, 1.09848195, 1.09822917,
       1.09892684, 1.09848939, 1.09865251, 1.09847266, 1.09853737,
       1.09842198, 1.09818383, 1.09856014, 1.09913662, 1.09857761,
       1.09886776, 1.09875283, 1.09904444, 1.0991445 , 1.09874141,
       1.09910501, 1.09927362, 1.09925825, 1.09902118, 1.09934396,
       1.09958903, 1.09985065, 1.09979708, 1.09940649, 1.09957884,
       1.0996549 , 1.10009278, 1.09975499, 1.10019419, 1.10026816,
       1.09976879, 1.10046228, 1.10069909, 1.10018915, 1.10042141,
       1.10063033, 1.10080337, 1.10086984, 1.100758  , 1.10084125,
       1.10096995, 1.10085894, 1.10048817, 1.10110616, 1.10118008,
       1.10119206, 1.1012494 , 1.10130364, 1.10118215, 1.10137