In [1]:
import numpy as np

### Mean
The mean is a useful measurement to get the center of a dataset. NumPy has a built-in function to calculate the average or mean of arrays: np.mean

In [2]:
store_one = np.array([2, 5, 8, 3, 4, 10, 15, 5])
store_two = np.array([3, 17, 18,  9,  2, 14, 10])
store_three = np.array([7, 5, 4, 3, 2, 7, 7])

store_one_avg = np.mean(store_one)
store_two_avg = np.mean(store_two)
store_three_avg = np.mean(store_three)
store_one_avg,store_two_avg,store_three_avg

(6.5, 10.428571428571429, 5.0)

In [4]:
class_year = np.array([1967, 1949, 2004, 1997, 1953, 1950, 1958, 1974, 1987, 2006, 2013, 1978, 1951, 1998, 1996, 1952, 2005, 2007, 2003, 1955, 1963, 1978, 2001, 2012, 2014, 1948, 1970, 2011, 1962, 1966, 1978, 1988, 2006, 1971, 1994, 1978, 1977, 1960, 2008, 1965, 1990, 2011, 1962, 1995, 2004, 1991, 1952, 2013, 1983, 1955, 1957, 1947, 1994, 1978, 1957, 2016, 1969, 1996, 1958, 1994, 1958, 2008, 1988, 1977, 1991, 1997, 2009, 1976, 1999, 1975, 1949, 1985, 2001, 1952, 1953, 1949, 2015, 2006, 1996, 2015, 2009, 1949, 2004, 2010, 2011, 2001, 1998, 1967, 1994, 1966, 1994, 1986, 1963, 1954, 1963, 1987, 1992, 2008, 1979, 1987])

millennials = np.mean(class_year >= 2005)
millennials

0.21

### Mean of 2D arrays


In [5]:
#Find total mean of 2D array
allergy_trials = np.array([[6, 1, 3, 8, 2], 
                           [2, 6, 3, 9, 8], 
                           [5, 2, 6, 9, 9]])

total_mean = np.mean(allergy_trials)
total_mean

5.266666666666667

Find mean across all rows individually of a 2D array

In [6]:
trial_mean = np.mean(allergy_trials,axis=1)
trial_mean

array([4. , 5.6, 6.2])

Find mean across all columns of 2D array

In [7]:
np.mean(allergy_trials,axis=0)

array([4.33333333, 3.        , 4.        , 8.66666667, 6.33333333])

Sort a numpy array

In [8]:
temps = np.array([86, 88, 94, 85, 97, 90, 87, 85, 94, 93, 92, 95, 98, 85, 94, 91, 97, 88, 87, 86, 99, 89, 89, 99, 88, 96, 93, 96, 85, 88, 191, 95, 96, 87, 99, 93, 90, 86, 87, 100, 187, 98, 101, 101, 96, 94, 96, 87, 86, 92, 98,94, 98, 90, 99, 96, 99, 86, 97, 98, 86, 90, 86, 94, 91, 88, 196, 195,93, 97, 199, 87, 87, 90, 90, 98, 88, 92, 97, 88, 85, 94, 88, 93, 198, 90, 91, 90, 92, 92])

sorted_temps = np.sort(temps)
sorted_temps

array([ 85,  85,  85,  85,  85,  86,  86,  86,  86,  86,  86,  86,  87,
        87,  87,  87,  87,  87,  87,  88,  88,  88,  88,  88,  88,  88,
        88,  89,  89,  90,  90,  90,  90,  90,  90,  90,  90,  91,  91,
        91,  92,  92,  92,  92,  92,  93,  93,  93,  93,  93,  94,  94,
        94,  94,  94,  94,  94,  95,  95,  96,  96,  96,  96,  96,  96,
        97,  97,  97,  97,  97,  98,  98,  98,  98,  98,  98,  99,  99,
        99,  99,  99, 100, 101, 101, 187, 191, 195, 196, 198, 199])

In [9]:
#The median is the middle value of a dataset that’s been ordered in terms of magnitude (from lowest to highest).
#Unlike mean median is not affected by outliers

In [10]:
# Percentiles
movies_watched = np.array([2, 3, 8, 0, 2, 4, 3, 1, 1, 0, 5, 1, 1, 7, 2])
first_quarter = np.percentile(movies_watched,25)
third_quarter = np.percentile(movies_watched,75)
interquartile_range = third_quarter - first_quarter

In [12]:
#standard deviation of a dataset can help us understand how spread out our dataset is.

#We can find the standard deviation of a dataset using the Numpy function np.std:
pumpkin = np.array([68, 1820, 1420, 2062, 704, 1156, 1857, 1755, 2092, 1384])

acorn_squash = np.array([20, 43, 99, 200, 12, 250, 58, 120, 230, 215])
pumpkin_std = np.std(pumpkin)
acorn_squash_std = np.std(acorn_squash)
pumpkin_std,acorn_squash_std

(611.3183785884406, 87.22505374031019)

In [13]:
rainfall = np.array([5.21, 3.76, 3.27, 2.35, 1.89, 1.55, 0.65, 1.06, 1.72, 3.35, 4.82, 5.11])

rain_mean = np.mean(rainfall)
rain_median = np.median(rainfall)
first_quarter = np.percentile(rainfall,25)
third_quarter = np.percentile(rainfall,75)
interquartile_range = third_quarter - first_quarter
rain_std = np.std(rainfall)
print(rain_mean,rain_median,first_quarter,third_quarter,interquartile_range,rain_std)

2.895 2.81 1.6775 4.025 2.3475 1.5267312577311483
